### ISSUE TITLE
no such file to load

### ISSUE THREAD

**Issue by stevenheidel** [neelance/java2ruby#1]
ruby -Ijava2ruby -Ijre4ruby -Iswt4ruby samples/swt/swt.rb
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- rjava/jni/linux-x86_32/jni_structs (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /home/steven/code/java2ruby-root/java2ruby/rjava.rb:17:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /home/steven/code/java2ruby-root/swt4ruby/swt4ruby.rb:1:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from samples/swt/swt.rb:1:in `<main>'

This is some amazing work btw

**Comment by stevenheidel** [comment]
Generate JNI structures for Linux 32 bit. Closed by fa6cb07ca004087428013e970597a0d68912205d
